=== KWARC/mwetoolkit/bin/old/dtd/mwetoolkit-patterns.dtd
<!ELEMENT patterns (pat*)>

<!ELEMENT pat (pat*,backpat*,w*,backw*,either*)>
<!ATTLIST pat
	id CDATA #IMPLIED
	repeat CDATA #IMPLIED
>

<!ELEMENT backpat EMPTY>
<!ATTLIST backpat
	id CDATA #REQUIRED
>

<!ELEMENT w EMPTY>
<!ATTLIST w
    surface CDATA #IMPLIED
    lemma CDATA #IMPLIED
    pos CDATA #IMPLIED
    syn CDATA #IMPLIED
    syndep CDATA #IMPLIED
    id CDATA #IMPLIED
>

<!--
  <!ATTLIST backw
      surface CDATA #IMPLIED
      lemma CDATA #IMPLIED
      pos CDATA #IMPLIED
      syn CDATA #IMPLIED
  >
-->

<!ELEMENT either (pat*)>
<!ATTLIST either
	id CDATA #IMPLIED
	repeat CDATA #IMPLIED
>

=== KWARC/mwetoolkit/toy2/gen/patterns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dict SYSTEM "dtd/mwetoolkit-patterns.dtd">
<patterns>
<!-- Any sequence of 1 or more nouns and adjectives followed by a noun -->
<pat>
  <pat repeat="+">
    <either>
      <pat><w pos="A"/></pat>
      <pat><w pos="N"/></pat>      
    </either>
  </pat>
  <w pos="N"/>
</pat>
</patterns>
