=== KWARC/mwetoolkit/dtd/mwetoolkit-candidates.dtd
<!--
################################################################################
#
# Copyright 2010 Carlos Ramisch
#
# mwetoolkit-candidates.dtd is part of mwetoolkit
#
# mwetoolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mwetoolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with mwetoolkit.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
-->
<!ELEMENT candidates (meta,cand*)>
<!ELEMENT meta (corpussize*,metafeat*,metatpclass*)>
<!ELEMENT corpussize EMPTY>
<!ATTLIST corpussize
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>
<!ELEMENT metafeat EMPTY>
<!-- type of metafeat should be integer, real, string or an 
enumeration of values between curly brackets, in the same style as
WEKA's arff file format -->
<!ATTLIST metafeat
    name CDATA #REQUIRED
    type CDATA #REQUIRED
>
<!ELEMENT metatpclass EMPTY>
<!-- type of metatpclass should be an enumeration of values between 
curly brackets, in the same style as WEKA's arff file format -->
<!ATTLIST metatpclass
    name CDATA #REQUIRED
    type CDATA #REQUIRED
>
<!ELEMENT cand (ngram,occurs?,features?,tpclass*)>
<!ATTLIST cand
    candid CDATA #IMPLIED
>
<!ELEMENT ngram (w+,freq*)>
<!ELEMENT w (freq)*>
<!ATTLIST w
    surface CDATA #IMPLIED
    lemma CDATA #IMPLIED
    pos CDATA #IMPLIED
> 
<!ELEMENT freq EMPTY>
<!ATTLIST freq
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>
<!ELEMENT occurs (ngram*)>
<!ELEMENT features (feat*)>
<!ELEMENT feat EMPTY>
<!ATTLIST feat
    name CDATA #REQUIRED
    value CDATA #REQUIRED
> 

<!ELEMENT tpclass EMPTY>
<!ATTLIST tpclass
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== KWARC/mwetoolkit/test/filetypes/corner-cases/candidates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE candidates SYSTEM "dtd/mwetoolkit-candidates.dtd">
<!-- MWETOOLKIT: filetype="XML" -->
<candidates >
<!-- =================================================
  Important things to test:
  * Values must be preserved (including escaping chars).
  * Candidate ordering (through `candid`) must be preserved.
  * Source IDs must be preserved.
  * Frequency info must be preserved.
================================================== -->
<meta>
</meta>
<cand candid="340">
    <ngram><w surface="Socialista" lemma="socialista" pos="NC" /> <w lemma="europeo" pos="ADJ" /> </ngram>
    <occurs>
    <ngram><w surface="socialistas" lemma="socialista" pos="NC" /> <w surface="europeos" lemma="europeo" pos="ADJ" /> <freq name="corpusX" value="1" /><sources ids="873:4,5"/>
</ngram>
    </occurs>
</cand>
<cand candid="335">
    <ngram><w lemma="período" pos="NC" /> <w lemma="de" pos="PREP" /> <w lemma="sesión" pos="NC" /> </ngram>
    <occurs>
    <ngram><w surface="período" lemma="período" pos="NC" /> <w surface="de" lemma="de" pos="PREP" /> <w surface="sesiones" lemma="sesión" pos="NC" /> <freq name="corpusY" value="3" /><sources ids="0:3,4,5;0:9,10,11;3:20,21,22"/>
</ngram>
    </occurs>
</cand>
<cand candid="350">
    <ngram><w lemma="abc&lt;d&#10;ef" pos="NC" /> <w lemma="añadir" pos="VLadj" /> </ngram>
    <occurs>
    <ngram><w surface="valor" lemma="valor" pos="NC" /> <w surface="bad-matching" /> <freq name="corpusX" value="1" /><sources ids="778:24,25"/>
</ngram>
    </occurs>
</cand>
</candidates>

=== KWARC/mwetoolkit/test/filetypes/xml-ref/candidates.PlainCandidates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE candidates SYSTEM "dtd/mwetoolkit-candidates.dtd">
<candidates >
<cand candid="1">
    <entry entryid="1">    <ngram><w surface="group" /> <w surface="a" /> </ngram></entry>
</cand>
<cand candid="2">
    <entry entryid="2">    <ngram><w surface="type" /> <w surface="a" /> </ngram></entry>
</cand>
<cand candid="3">
    <entry entryid="3">    <ngram><w surface="rich" /> <w surface="person" /> </ngram></entry>
</cand>
<cand candid="4">
    <entry entryid="4">    <ngram><w surface="wealthy" /> <w surface="person" /> </ngram></entry>
</cand>
<cand candid="5">
    <entry entryid="5">    <ngram><w surface="body" /> <w surface="of" /> <w surface="work" /> </ngram></entry>
</cand>
<cand candid="6">
    <entry entryid="6">    <ngram><w surface="prison" /> <w surface="term" /> </ngram></entry>
</cand>
<cand candid="7">
    <entry entryid="7">    <ngram><w surface="number" /> <w surface="1" /> </ngram></entry>
</cand>
<cand candid="8">
    <entry entryid="8">    <ngram><w surface="trade" /> <w surface="good" /> </ngram></entry>
</cand>
<cand candid="9">
    <entry entryid="9">    <ngram><w surface="selective" /> <w surface="information" /> </ngram></entry>
</cand>
<cand candid="10">
    <entry entryid="10">    <ngram><w surface="written" /> <w surface="report" /> </ngram></entry>
</cand>
<cand candid="11">
    <entry entryid="11">    <ngram><w surface="elbow" /> <w surface="room" /> </ngram></entry>
</cand>
<cand candid="12">
    <entry entryid="12">    <ngram><w surface="inspection" /> <w surface="and" /> <w surface="repair" /> </ngram></entry>
</cand>
<cand candid="13">
    <entry entryid="13">    <ngram><w surface="service" /> <w surface="of" /> <w surface="process" /> </ngram></entry>
</cand>
<cand candid="14">
    <entry entryid="14">    <ngram><w surface="armed" /> <w surface="service" /> </ngram></entry>
</cand>
<cand candid="15">
    <entry entryid="15">    <ngram><w surface="military" /> <w surface="service" /> </ngram></entry>
</cand>
<cand candid="16">
    <entry entryid="16">    <ngram><w surface="divine" /> <w surface="service" /> </ngram></entry>
</cand>
<cand candid="17">
    <entry entryid="17">    <ngram><w surface="religious" /> <w surface="service" /> </ngram></entry>
</cand>
<cand candid="18">
    <entry entryid="18">    <ngram><w surface="first" /> <w surface="gear" /> </ngram></entry>
</cand>
<cand candid="19">
    <entry entryid="19">    <ngram><w surface="low" /> <w surface="gear" /> </ngram></entry>
</cand>
<cand candid="20">
    <entry entryid="20">    <ngram><w surface="business" /> <w surface="enterprise" /> </ngram></entry>
</cand>
<cand candid="21">
    <entry entryid="21">    <ngram><w surface="right" /> <w surface="field" /> </ngram></entry>
</cand>
<cand candid="22">
    <entry entryid="22">    <ngram><w surface="blank" /> <w surface="space" /> </ngram></entry>
</cand>
<cand candid="23">
    <entry entryid="23">    <ngram><w surface="record" /> <w surface="book" /> </ngram></entry>
</cand>
<cand candid="24">
    <entry entryid="24">    <ngram><w surface="guinea" /> <w surface="pig" /> </ngram></entry>
</cand>
<cand candid="25">
    <entry entryid="25">    <ngram><w surface="book" /> <w surface="binding" /> </ngram></entry>
</cand>
<cand candid="26">
    <entry entryid="26">    <ngram><w surface="chemical" /> <w surface="group" /> </ngram></entry>
</cand>
<cand candid="27">
    <entry entryid="27">    <ngram><w surface="surface" /> <w surface="area" /> </ngram></entry>
</cand>
<cand candid="28">
    <entry entryid="28">    <ngram><w surface="line" /> <w surface="of" /> <w surface="work" /> </ngram></entry>
</cand>
<cand candid="29">
    <entry entryid="29">    <ngram><w surface="phone" /> <w surface="number" /> </ngram></entry>
</cand>
<cand candid="30">
    <entry entryid="30">    <ngram><w surface="telephone" /> <w surface="number" /> </ngram></entry>
</cand>
<cand candid="31">
    <entry entryid="31">    <ngram><w surface="monetary" /> <w surface="value" /> </ngram></entry>
</cand>
<cand candid="32">
    <entry entryid="32">    <ngram><w surface="facial" /> <w surface="expression" /> </ngram></entry>
</cand>
<cand candid="33">
    <entry entryid="33">    <ngram><w surface="theatrical" /> <w surface="role" /> </ngram></entry>
</cand>
<cand candid="34">
    <entry entryid="34">    <ngram><w surface="hoi" /> <w surface="polloi" /> </ngram></entry>
</cand>
<cand candid="35">
    <entry entryid="35">    <ngram><w surface="the" /> <w surface="great" /> <w surface="unwashed" /> </ngram></entry>
</cand>
<cand candid="36">
    <entry entryid="36">    <ngram><w surface="great" /> <w surface="britain" /> </ngram></entry>
</cand>
<cand candid="37">
    <entry entryid="37">    <ngram><w surface="course" /> <w surface="of" /> <w surface="instruction" /> </ngram></entry>
</cand>
<cand candid="38">
    <entry entryid="38">    <ngram><w surface="course" /> <w surface="of" /> <w surface="study" /> </ngram></entry>
</cand>
<cand candid="39">
    <entry entryid="39">    <ngram><w surface="public" /> <w surface="figure" /> </ngram></entry>
</cand>
<cand candid="40">
    <entry entryid="40">    <ngram><w surface="stage" /> <w surface="business" /> </ngram></entry>
</cand>
<cand candid="41">
    <entry entryid="41">    <ngram><w surface="news" /> <w surface="report" /> </ngram></entry>
</cand>
<cand candid="42">
    <entry entryid="42">    <ngram><w surface="write" /> <w surface="up" /> </ngram></entry>
</cand>
<cand candid="43">
    <entry entryid="43">    <ngram><w surface="political" /> <w surface="campaign" /> </ngram></entry>
</cand>
<cand candid="44">
    <entry entryid="44">    <ngram><w surface="nursing" /> <w surface="home" /> </ngram></entry>
</cand>
<cand candid="45">
    <entry entryid="45">    <ngram><w surface="rest" /> <w surface="home" /> </ngram></entry>
</cand>
<cand candid="46">
    <entry entryid="46">    <ngram><w surface="musical" /> <w surface="accompaniment" /> </ngram></entry>
</cand>
<cand candid="47">
    <entry entryid="47">    <ngram><w surface="insurance" /> <w surface="policy" /> </ngram></entry>
</cand>
<cand candid="48">
    <entry entryid="48">    <ngram><w surface="business" /> <w surface="firm" /> </ngram></entry>
</cand>
<cand candid="49">
    <entry entryid="49">    <ngram><w surface="government" /> <w surface="issue" /> </ngram></entry>
</cand>
<cand candid="50">
    <entry entryid="50">    <ngram><w surface="military" /> <w surface="issue" /> </ngram></entry>
</cand>
</candidates>
