=== KWARC/mwetoolkit/dtd/mwetoolkit-dict.dtd
<!--
################################################################################
#
# Copyright 2010 Carlos Ramisch
#
# mwetoolkit-dict.dtd is part of mwetoolkit
#
# mwetoolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mwetoolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with mwetoolkit.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
-->
<!ELEMENT dict (meta,entry*)>
<!ELEMENT meta (corpussize*,metafeat*)>
<!-- type of metafeat should be integer, real, string or an 
enumeration of values between curly brackets, in the same style as
WEKA's arff file format -->
<!ELEMENT metafeat EMPTY>
<!ATTLIST metafeat
    name CDATA #REQUIRED
    type CDATA #REQUIRED
>
<!ELEMENT entry (ngram,features?)>
<!ATTLIST entry
    entryid CDATA #IMPLIED
>
<!ELEMENT ngram (w+,freq*)>
<!ELEMENT w (freq)*>
<!ATTLIST w
    surface CDATA #IMPLIED
    lemma CDATA #IMPLIED
    pos CDATA #IMPLIED
> 
<!ELEMENT freq EMPTY>
<!ATTLIST freq
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>
<!ELEMENT features (feat*)>
<!ELEMENT feat EMPTY>
<!ATTLIST feat
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== KWARC/mwetoolkit/toy/genia/test/tail_patterns_small.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dict SYSTEM "dtd/mwetoolkit-dict.dtd">
<dict>
<entry entryid="32">
    <ngram><w pos="FW" /> <w pos="FW" /> </ngram>
</entry>
<entry entryid="33">
    <ngram><w pos="FW" /> <w pos="FW" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="34">
    <ngram><w pos="N" /> <w pos="A" /> <w pos="A" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="35">
    <ngram><w pos="N" /> <w pos="A" /> <w pos="A" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="36">
    <ngram><w pos="N" /> <w pos="A" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="37">
    <ngram><w pos="N" /> <w pos="A" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="38">
    <ngram><w pos="N" /> <w pos="A" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="39">
    <ngram><w pos="N" /> <w pos="A" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="40">
    <ngram><w pos="N" /> <w pos="A" /> <w pos="N" /> <w pos="NUM" /> </ngram>
</entry>
<entry entryid="41">
    <ngram><w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="42">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="A" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="43">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="A" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="44">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="A" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="45">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="46">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="A" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="47">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="48">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="49">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="50">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> <w pos="NUM" /> </ngram>
</entry>
<entry entryid="51">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="NUM" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="52">
    <ngram><w pos="N" /> <w pos="N" /> <w pos="NUM" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="53">
    <ngram><w pos="N" /> <w pos="NUM" /> </ngram>
</entry>
<entry entryid="54">
    <ngram><w pos="N" /> <w pos="NUM" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="55">
    <ngram><w pos="N" /> <w pos="NUM" /> <w pos="N" /> <w pos="N" /> <w pos="N" /> </ngram>
</entry>
<entry entryid="56">
    <ngram><w pos="N" /> <w pos="NUM" /> <w pos="P" /> <w pos="NUM" /> </ngram>
</entry>
</dict>

=== KWARC/mwetoolkit/toy/genia/patterns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dict SYSTEM "dtd/mwetoolkit-dict.dtd">
<dict>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="N"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="CC"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="CC"/><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="CC"/><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="CC"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="CC"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="A"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="NUM"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="NUM"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="NUM"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="N"/><w pos="NUM"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="NUM"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="N"/><w pos="NUM"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="NUM"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="V"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="A"/><w pos="V"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="FW"/><w pos="FW"/></ngram></entry>
<entry><ngram><w pos="FW"/><w pos="FW"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="A"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="A"/><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="A"/><w pos="N"/><w pos="NUM"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="A"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="A"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="N"/><w pos="A"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="N"/><w pos="N"/><w pos="NUM"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="NUM"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="N"/><w pos="NUM"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="NUM"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="NUM"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="NUM"/><w pos="N"/><w pos="N"/><w pos="N"/></ngram></entry>
<entry><ngram><w pos="N"/><w pos="NUM"/><w pos="P"/><w pos="NUM"/></ngram></entry>
</dict>

=== KWARC/mwetoolkit/toy/greek/gr_patterns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dict SYSTEM "dtd/mwetoolkit-dict.dtd">
<dict>
<entry><ngram><w pos="AJ"/><w pos="N"/></ngram></entry> <!-- φορητός υπολογιστής-->
<entry><ngram><w pos="N"/><w pos="AJ"/></ngram></entry> <!-- ηλίου φαεινότερο, χρόνια πολλά-->
<entry><ngram><w pos="N"/><w pos="N"/></ngram></entry> <!-- κράτος μέλος, υπουργείο εσωτερικών-->
<entry><ngram><w pos="N"/><w pos="DT"/><w pos="N"/></ngram></entry> <!-- φαινόμενο του θερμοκηπίου-->
<entry><ngram><w pos="N"/><w pos="AJ"/><w pos="N"/></ngram></entry> <!-- τεχνολογία υψηλής ευκρίνειας-->
<entry><ngram><w pos="N"/><w pos="P"/><w pos="N"/></ngram></entry> <!-- φόνος εκ προμελέτης-->
<entry><ngram><w pos="V"/><w pos="N"/></ngram></entry> <!-- βρέχει καρέκλες -->
<entry><ngram><w pos="V"/><w pos="DT"/><w pos="N"/></ngram></entry> <!-- τρέχει η βρύση -->
<entry><ngram><w pos="V"/><w pos="P"/><w pos="N"/></ngram></entry> <!-- θέτω σε κίνδυνο -->
<entry><ngram><w pos="P"/><w pos="N"/></ngram></entry> <!-- επί τάπητος -->
<entry><ngram><w pos="P"/><w pos="AJ"/></ngram></entry> <!-- εν ολίγοις -->
<entry><ngram><w pos="P"/><w pos="V"/></ngram></entry> <!-- πέρα βρέχει -->
<entry><ngram><w pos="P"/><w pos="DT"/><w pos="AJ"/></ngram></entry> <!-- με το καλό -->
<entry><ngram><w pos="P"/><w pos="N"/><w pos="N"/></ngram></entry> <!-- κατά φαντασίαν ασθενής -->
<entry><ngram><w pos="P"/><w pos="AJ"/><w pos="N"/></ngram></entry> <!-- εν πάση περιπτώσει -->
<entry><ngram><w pos="ADV"/><w pos="V"/></ngram></entry> <!-- καλώς όρισες -->
<!-- <entry><ngram><w pos="ADV"/><w pos="CJ"/><w pos="ADV"/></ngram></entry> καλώς ή κακώς -->
<!-- <entry><ngram><w pos="CJ"/><w pos="DT"/><w pos="N"/></ngram></entry> και του χρόνου -->
<!-- <entry><ngram><w pos="P"/><w pos="N"/><w pos="CJ"/><w pos="P"/><w pos="N"/></ngram></entry>  με νύχια και με δόντια -->
</dict>

=== KWARC/mwetoolkit/toy/genia/test/tail_reference_small.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dict SYSTEM "dtd/mwetoolkit-dict.dtd">
<dict>
<entry entryid="1984">
    <ngram><w surface="viral" /> <w surface="transcriptional" /> <w surface="transactivator" /> </ngram>
</entry>
<entry entryid="1985">
    <ngram><w surface="virally" /> <w surface="transformed" /> <w surface="cell" /> </ngram>
</entry>
<entry entryid="1986">
    <ngram><w surface="virus" /> <w surface="production" /> </ngram>
</entry>
<entry entryid="1987">
    <ngram><w surface="virus" /> <w surface="transcription" /> </ngram>
</entry>
<entry entryid="1988">
    <ngram><w surface="virus" /> <w surface="transformed" /> <w surface="cell" /> </ngram>
</entry>
<entry entryid="1989">
    <ngram><w surface="vitamin" /> <w surface="d" /> <w surface="receptor" /> </ngram>
</entry>
<entry entryid="1990">
    <ngram><w surface="vitamin" /> <w surface="d" /> <w surface="receptor" /> <w surface="gene" /> </ngram>
</entry>
<entry entryid="1991">
    <ngram><w surface="vitamin" /> <w surface="d" /> <w surface="receptor" /> <w surface="messenger" /> <w surface="ribonucleic" /> <w surface="acid" /> </ngram>
</entry>
<entry entryid="1992">
    <ngram><w surface="vitamin" /> <w surface="d3" /> </ngram>
</entry>
<entry entryid="1993">
    <ngram><w surface="vitamin" /> <w surface="d3" /> <w surface="mediated" /> </ngram>
</entry>
<entry entryid="1994">
    <ngram><w surface="vitamin" /> <w surface="d3" /> <w surface="mediated" /> <w surface="repression" /> </ngram>
</entry>
<entry entryid="1995">
    <ngram><w surface="vitamin" /> <w surface="d3" /> <w surface="receptor" /> </ngram>
</entry>
<entry entryid="1996">
    <ngram><w surface="vitamin" /> <w surface="e" /> </ngram>
</entry>
<entry entryid="1997">
    <ngram><w surface="vitamin" /> <w surface="e" /> <w surface="therapy" /> </ngram>
</entry>
<entry entryid="1998">
    <ngram><w surface="western" /> <w surface="blot" /> <w surface="analysis" /> </ngram>
</entry>
<entry entryid="1999">
    <ngram><w surface="western" /> <w surface="blotting" /> </ngram>
</entry>
<entry entryid="2000">
    <ngram><w surface="whole" /> <w surface="cell" /> <w surface="binding" /> <w surface="assay" /> </ngram>
</entry>
<entry entryid="2001">
    <ngram><w surface="x" /> <w surface="linked" /> <w surface="severe" /> <w surface="combined" /> <w surface="immunodeficiency" /> </ngram>
</entry>
<entry entryid="2002">
    <ngram><w surface="xscid" /> <w surface="like" /> <w surface="phenotype" /> </ngram>
</entry>
<entry entryid="2003">
    <ngram><w surface="yeast" /> <w surface="transactivator" /> <w surface="gal4" /> </ngram>
</entry>
<entry entryid="2004">
    <ngram><w surface="yt" /> <w surface="cell" /> <w surface="line" /> </ngram>
</entry>
<entry entryid="2005">
    <ngram><w surface="zinc" /> <w surface="finger" /> </ngram>
</entry>
<entry entryid="2006">
    <ngram><w surface="zinc" /> <w surface="finger" /> <w surface="protein" /> </ngram>
</entry>
<entry entryid="2007">
    <ngram><w surface="zinc" /> <w surface="finger" /> <w surface="protein" /> <w surface="binding" /> <w surface="region" /> </ngram>
</entry>
<entry entryid="2008">
    <ngram><w surface="zip" /> <w surface="site" /> </ngram>
</entry>
</dict>
