=== KWARC/mwetoolkit/dtd/mwetoolkit-corpus.dtd
<!--
################################################################################
#
# Copyright 2011 Carlos Ramisch, Vitor de Araujo
#
# mwetoolkit-corpus.dtd is part of mwetoolkit
#
# mwetoolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mwetoolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with mwetoolkit.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
-->
<!ELEMENT corpus (s)*>
<!ELEMENT s (w)*>
<!ATTLIST s
    s_id CDATA #IMPLIED
>
<!ELEMENT w EMPTY>
<!ATTLIST w
    surface CDATA #REQUIRED
    lemma CDATA #IMPLIED
    pos CDATA #IMPLIED
    syn CDATA #IMPLIED 
    dep CDATA #IMPLIED     
> 
<!-- surface: Surface form of a word, like each word in the sentence "He went to the streets"
     lemma: Lemmatised (original) form of a word, like each lemma in the sentence "he go to the street"
     pos: Morphosyntactic category of a word, like each class name (N-Noun, V-Verb, etc.) in the sentence "PP V P DT N"
     == The following two attributes may be empty "" or have multiple values, in which case they will be separated by ";"
     syn: Syntax information in any formalism you like, for instance the dependency relation in the sentence "subj - - det to_pcomp"
     dep: Index of the word in the sentence on which this word depends with the "syn" relation, like in "2 - - 5 3". The index starts at 1.
-->

=== KWARC/mwetoolkit/test/conll/ToDo/f2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE corpus SYSTEM "dtd/mwetoolkit-corpus.dtd">
<corpus >
<s s_id="0"><w surface="Cathy" lemma="Cathy" pos="N" syn="su:2" /> <w surface="zag" lemma="zie" pos="V" syn="ROOT:0" /> <w surface="hen" lemma="hen" pos="Pron" syn="obj1:2" /> <w surface="wild" lemma="wild" pos="Adj" syn="mod:5" /> <w surface="zwaaien" lemma="zwaai" pos="N" syn="vc:2" /> <w surface="." lemma="." pos="Punc" syn="punct:5" /> </s>
</corpus>
