=== KWARC/mwetoolkit/dtd/mwttoolkit-patterns.dtd
<!ELEMENT patterns (pattern)*>
<!ELEMENT pattern (w)*>
<!ELEMENT w EMPTY>
<!ATTLIST w
    surface CDATA #IMPLIED
    lemma CDATA #IMPLIED
    pos CDATA #IMPLIED   
>

=== KWARC/mwetoolkit/toy/genia/reference.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE corpus SYSTEM "mwttoolkit-patterns.dtd">
<patterns>
<pattern><w surface="&quot;" /><w surface="giant" /><w surface="&quot;" /><w surface="platelet" /></pattern>
<pattern><w surface="&quot;" /><w surface="n" /><w surface="end" /><w surface="rule" /><w surface="&quot;" /><w surface="ligase" /></pattern>
<pattern><w surface="1,25" /><w surface="dihydroxyvitamin" /><w surface="d3" /></pattern>
<pattern><w surface="1,25" /><w surface="dihydroxyvitamin" /><w surface="d3" /></pattern>
<pattern><w surface="1,25" /><w surface="oh" /><w surface="2d3" /><w surface="dependent" /><w surface="modulation" /></pattern>
<pattern><w surface="1,25" /><w surface="oh" /><w surface="2d3" /><w surface="mediated" /><w surface="repression" /></pattern>
<pattern><w surface="1,25" /><w surface="oh" /><w surface="2d3" /><w surface="receptor" /></pattern>
<pattern><w surface="1,25" /><w surface="oh" /><w surface="2d3" /><w surface="synthesis" /></pattern>
<pattern><w surface="1.5" /><w surface="g" /><w surface="metyrapone" /></pattern>
<pattern><w surface="10" /><w surface="microm" /><w surface="kn" /><w surface="62" /></pattern>
<pattern><w surface="105" /><w surface="kda" /></pattern>
<pattern><w surface="p130" /><w surface="kd" /><w surface="protein" /></pattern>
<pattern><w surface="141" /><w surface="bp" /><w surface="further" /><w surface="upstream" /></pattern>
<pattern><w surface="15" /><w surface="lipoxygenase" /><w surface="gene" /></pattern>
<pattern><w surface="15" /><w surface="lox" /><w surface="gene" /></pattern>
<pattern><w surface="2,738" /><w surface="nucleotide" /></pattern>
<pattern><w surface="2.3" /><w surface="kb" /><w surface="lcr" /></pattern>
<pattern><w surface="200" /><w surface="bp" /><w surface="enhancer" /><w surface="domain" /></pattern>
<pattern><w surface="24" /><w surface="hydroxylase" /><w surface="mrna" /></pattern>
<pattern><w surface="24,25" /><w surface="dihydroxyvitamin" /><w surface="d3" /></pattern>
<pattern><w surface="25" /><w surface="hydroxyvitamin" /><w surface="d3" /></pattern>
<pattern><w surface="25" /><w surface="oh" /><w surface="d3" /><w surface="transport" /></pattern>
<pattern><w surface="253" /><w surface="nucleotide" /></pattern>
<pattern><w surface="28" /><w surface="bp" /><w surface="core" /><w surface="region" /></pattern>
<pattern><w surface="3" /><w surface="4" /><w surface="b" /><w surface="cell" /><w surface="line" /></pattern>
<pattern><w surface="3'" /><w surface="portion" /></pattern>
<pattern><w surface="30" /><w surface="base" /><w surface="pair" /><w surface="upstream" /></pattern>
<pattern><w surface="32" /><w surface="34" /><w surface="kda" /><w surface="protein" /></pattern>
<pattern><w surface="320" /><w surface="kda" /><w surface="species" /></pattern>
<pattern><w surface="327" /><w surface="aa" /><w surface="protein" /></pattern>
<pattern><w surface="32p" /><w surface="labeled" /><w surface="ht" /><w surface="2" /><w surface="cell" /></pattern>
<pattern><w surface="33" /><w surface="kda" /><w surface="protein" /></pattern>
<pattern><w surface="380" /><w surface="bp" /><w surface="upstream" /></pattern>
<pattern><w surface="4" /><w surface="12" /><w surface="t" /><w surface="cell" /></pattern>
<pattern><w surface="4" /><w surface="5" /><w surface="t" /><w surface="cell" /><w surface="line" /></pattern>
<pattern><w surface="40" /><w surface="bp" /><w surface="region" /></pattern>
<pattern><w surface="47" /><w surface="to" /><w surface="40" /><w surface="upstream" /></pattern>
<pattern><w surface="5" /><w surface="12" /><w surface="t" /><w surface="cell" /></pattern>
<pattern><w surface="5'" /><w surface="deletion" /><w surface="construct" /></pattern>
<pattern><w surface="5'" /><w surface="end" /><w surface="of" /><w surface="human" /><w surface="thromboxane" /><w surface="receptor" /><w surface="gene" /></pattern>
<pattern><w surface="5'" /><w surface="flanking" /><w surface="dna" /></pattern>
<pattern><w surface="5'" /><w surface="flanking" /><w surface="genomic" /><w surface="clone" /></pattern>
<pattern><w surface="5'" /><w surface="flanking" /><w surface="region" /></pattern>
<pattern><w surface="5'" /><w surface="flanking" /><w surface="region" /></pattern>
<pattern><w surface="5'" /><w surface="portion" /></pattern>
<pattern><w surface="50" /><w surface="kda" /><w surface="nf" /><w surface="kappa" /><w surface="b" /></pattern>
<pattern><w surface="503" /><w surface="amino" /><w surface="acid" /><w surface="long" /><w surface="acidic" /><w surface="protein" /></pattern>
<pattern><w surface="560" /><w surface="bp" /><w surface="upstream" /></pattern>
<pattern><w surface="60" /><w surface="kda" /><w surface="precursor" /></pattern>
<pattern><w surface="69" /><w surface="bp" /><w surface="upstream" /></pattern>
<pattern><w surface="93" /><w surface="and" /><w surface="150" /><w surface="nucleotide" /><w surface="upstream" /></pattern>
<pattern><w surface="97" /><w surface="kda" /><w surface="ca" /><w surface="2+" /><w surface="atpase" /></pattern>
<pattern><w surface="97" /><w surface="kda" /><w surface="ca" /><w surface="2+" /><w surface="atpase" /><w surface="target" /></pattern>
<pattern><w surface="absorptive" /><w surface="hypercalciuria" /></pattern>
<pattern><w surface="absorptive" /><w surface="hypercalciuric" /><w surface="patient" /></pattern>
<pattern><w surface="acth" /><w surface="stimulation" /><w surface="test" /></pattern>
<pattern><w surface="actin" /><w surface="filament" /></pattern>
<pattern><w surface="actinomycin" /><w surface="d" /></pattern>
<pattern><w surface="actinomycin" /><w surface="d" /><w surface="pulse" /><w surface="experiment" /></pattern>
<pattern><w surface="activated" /><w surface="cell" /></pattern>
<pattern><w surface="activated" /><w surface="endothelial" /><w surface="cell" /></pattern>
<pattern><w surface="activated" /><w surface="ht" /><w surface="2" /><w surface="cell" /></pattern>
<pattern><w surface="activated" /><w surface="il" /><w surface="2" /><w surface="expression" /></pattern>
<pattern><w surface="activated" /><w surface="lymphocyte" /></pattern>
<pattern><w surface="activated" /><w surface="normal" /><w surface="human" /><w surface="lymphocyte" /></pattern>
<pattern><w surface="activated" /><w surface="t" /><w surface="cell" /></pattern>
<pattern><w surface="activation" /><w surface="antigen" /></pattern>
<pattern><w surface="activation" /><w surface="domain" /></pattern>
<pattern><w surface="activator" /><w surface="protein" /><w surface="2" /></pattern>
<pattern><w surface="activator" /><w surface="protein" /><w surface="2" /><w surface="binding" /><w surface="consensus" /><w surface="site" /></pattern>
<pattern><w surface="acute" /><w surface="ccl4" /><w surface="induced" /><w surface="hepatic" /><w surface="injury" /></pattern>
<pattern><w surface="acute" /><w surface="fulminant" /><w surface="hepatitis" /></pattern>
<pattern><w surface="acute" /><w surface="hepatic" /><w surface="injury" /></pattern>
<pattern><w surface="acute" /><w surface="myocardial" /><w surface="infarction" /></pattern>
<pattern><w surface="adaptive" /><w surface="change" /></pattern>
<pattern><w surface="adenovirus" /><w surface="e1b" /><w surface="19" /><w surface="kda" /></pattern>
<pattern><w surface="adenovirus" /><w surface="transformed" /><w surface="cell" /></pattern>
<pattern><w surface="adherent" /><w surface="human" /><w surface="igg" /></pattern>
<pattern><w surface="adult" /><w surface="level" /></pattern>
<pattern><w surface="adult" /><w surface="mouse" /><w surface="tissue" /></pattern>
<pattern><w surface="adult" /><w surface="red" /><w surface="blood" /><w surface="cell" /></pattern>
<pattern><w surface="adult" /><w surface="t" /><w surface="cell" /></pattern>
<pattern><w surface="adult" /><w surface="t" /><w surface="cell" /><w surface="leukemia" /></pattern>
<pattern><w surface="adult" /><w surface="t" /><w surface="cell" /><w surface="leukemia" /></pattern>
<pattern><w surface="adult" /><w surface="t" /><w surface="cell" /><w surface="leukemia" /><w surface="patient" /></pattern>
<pattern><w surface="agonistic" /><w surface="anti" /><w surface="cd30" /><w surface="monoclonal" /><w surface="antibody" /></pattern>
<pattern><w surface="aids" /><w surface="associated" /><w surface="disorder" /></pattern>
<pattern><w surface="airway" /><w surface="epithelial" /><w surface="cell" /></pattern>
<pattern><w surface="alkaline" /><w surface="phosphatase" /></pattern>
<pattern><w surface="alpha" /><w surface="tocopherol" /><w surface="treatment" /></pattern>
<pattern><w surface="alternating" /><w surface="rcgcrygcgy" /><w surface="consensus" /></pattern>
<pattern><w surface="alternative" /><w surface="splicing" /></pattern>
<pattern><w surface="altruistic" /><w surface="suicide" /></pattern>
<pattern><w surface="amino" /><w surface="acid" /><w surface="279" /></pattern>
<pattern><w surface="amino" /><w surface="acid" /><w surface="domain" /></pattern>
<pattern><w surface="amino" /><w surface="terminal" /><w surface="region" /></pattern>
<pattern><w surface="aminothiol" /><w surface="compound" /></pattern>
<pattern><w surface="aml" /><w surface="1" /><w surface="protein" /></pattern>
<pattern><w surface="androgen" /><w surface="receptor" /></pattern>
<pattern><w surface="androgen" /><w surface="receptor" /><w surface="behavior" /></pattern>
<pattern><w surface="animal" /><w surface="and" /><w surface="human" /><w surface="population" /></pattern>
<pattern><w surface="animal" /><w surface="model" /></pattern>
<pattern><w surface="animal" /><w surface="study" /></pattern>
<pattern><w surface="anti" /><w surface="apoptotic" /><w surface="protein" /></pattern>
<pattern><w surface="anti" /><w surface="c" /><w surface="ebp" /><w surface="beta" /></pattern>
<pattern><w surface="anti" /><w surface="c" /><w surface="ebp" /><w surface="beta" /><w surface="ab" /></pattern>
<pattern><w surface="anti" /><w surface="cd2" /><w surface="mediated" /><w surface="activation" /></pattern>
